title: GTU Rover
email: rover@gtu.edu.tr
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username: github.com/gtu-rover

# Build settings
theme: minima
plugins:
  - jekyll-feed
    
# team order is important
danisman: Recep Önler
members:
  - electronics:
    - Alpcan Soydaş
    - Toprak Alp
    - Asuman Sare Ergut
    - Yusuf Günan
    - Muhammed Cemal Eryiğit
    - Alperen Ürey
    - Ogün Uygar Yıldırım
    - Muhammet Fatih Keskin
    - Alperen Karataş
  - software:
    - Harun Albayrak
    - Fatih Kaan Salgır
    - Ömer Faruk Sayar
    - Baran Şahin
    - Oğuzhan Yaşar
    - Halil İbrahim İlhan
    - Ozan Yıldız
    - Yunus Emre Geyik
    - Muhammed Sevinçtekin
  - mechanical:
    - Muhammed Eymen Sunduvaç
    - Yunus Emre Eyüboğlu
    - Yunus Koman
    - Bilal Akdağ
    - Emre Şentürk
  - science:
    - Oğuz Güçlü
    - Buse Aktürk
    - Reyhan Bolat
  - sponsorship:
    - Doğan Turan
    - Saliha Kansız


# sponsorlar:
#   - sponsor_category: Altın
#   - sponsor_category: Gumus

exclude: 
  - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
  - Gemfile
  - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
